"""Peak data: render, parse, and scan 8-bit min/max waveform .dat files.

The wave editor renders the album waveform on a `<canvas>` from a single
`.peaks.dat` file generated by BBC `audiowaveform` against the album's
concat cache (`in-progress/<album_id>/.cache/concat.flac`). The same .dat
backs silence detection (server-side scan, no ffmpeg subprocess) and the
approximate peak readout shown in the editor before the user clicks
measure.

Format: BBC audiowaveform v2 binary. Header is 24 bytes (little-endian)
followed by `2 * length * channels` signed int8 min/max samples. We always
pre-mix to mono via `ffmpeg -ac 1` so the body is exactly `2 * length`
bytes. See https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md.
"""
import math
import os
import struct
import subprocess
from pathlib import Path
from typing import Optional

# Resolution of the precomputed peak data:
#   * `-z 256` = 256 input samples per bucket (≈ 2.67 ms at 96 kHz). With a
#     2400 px canvas a 0.5 s window puts ~13 px under each bucket — visibly
#     stair-stepped at deepest zoom but still 50× finer than the 0.01 s
#     split-cut display precision the editor exposes.
#   * `-b 8` = int8 min/max per bucket. 256 amplitude levels covers the
#     140 px canvas height with headroom and halves the .dat size vs. -b 16.
PEAKS_SAMPLES_PER_PIXEL = 256
PEAKS_BITS = 8


def render_peaks(src: Path, out_dat: Path) -> None:
    """Run audiowaveform directly against `src` (a FLAC) and produce an
    8-bit mono `.peaks.dat` at `out_dat`. Atomic via .tmp + os.replace so a
    crash mid-render leaves either the previous file or nothing.

    audiowaveform reads FLAC natively through libsndfile and downmixes to
    a single mono envelope by default — we let it do that. We previously
    tried to pre-mix via `ffmpeg | audiowaveform` over stdin, but ffmpeg
    can't seek back to write a WAV header's real frame count over a pipe
    so audiowaveform reads `frames=INT32_MAX` and silently produces no
    output.
    """
    out_dat.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_dat.with_suffix(".dat.tmp")
    proc = subprocess.run(
        ["audiowaveform",
         "-i", str(src),
         "-o", str(tmp),
         "-z", str(PEAKS_SAMPLES_PER_PIXEL),
         "-b", str(PEAKS_BITS),
         "--output-format", "dat"],
        capture_output=True, check=False,
    )
    if proc.returncode != 0:
        try: tmp.unlink(missing_ok=True)
        except Exception: pass
        msg = (proc.stderr or proc.stdout or b"").decode("utf-8", errors="replace")[:500]
        raise RuntimeError(f"audiowaveform failed: {msg or 'unknown error'}")
    if not tmp.exists() or tmp.stat().st_size <= 20:
        try: tmp.unlink(missing_ok=True)
        except Exception: pass
        raise RuntimeError("audiowaveform produced empty output")
    os.replace(tmp, out_dat)


def is_fresh(dat: Path, src: Path) -> bool:
    """Cache-validity check used by callers: the .dat counts as fresh iff
    it exists and is at least as new as its source FLAC. Returns False if
    either path is missing — defensive against stat() races."""
    try:
        return dat.exists() and dat.stat().st_mtime >= src.stat().st_mtime
    except FileNotFoundError:
        return False


# ── Header parser ────────────────────────────────────────────────────────
#
# audiowaveform's binary dat has two header layouts (see WaveformBuffer.cpp:
# `version = channels_ == 1 ? 1 : 2`):
#
#   v1 (mono, 20-byte header, body starts at offset 20):
#     i32 version=1, u32 flags, i32 sample_rate, i32 samples_per_pixel,
#     u32 length
#
#   v2 (multi-channel, 24-byte header, body starts at offset 24):
#     i32 version=2, u32 flags, i32 sample_rate, i32 samples_per_pixel,
#     u32 length, i32 channels
#
# audiowaveform downmixes to mono by default, so the common case is v1.
# Misreading a v1 file as v2 gives a wildly bogus `channels` field
# (the first 4 body bytes interpreted as int32) — that was the root cause
# of the "Invalid typed array length" error in the wave editor.

def read_header(dat: Path) -> dict:
    """Parse the audiowaveform v1 or v2 binary header.

    Returns a dict with `version`, `flags`, `sample_rate`,
    `samples_per_pixel`, `length`, `channels`, `bits`, and `header_size`
    (where the body starts).
    """
    with open(dat, "rb") as f:
        head = f.read(24)
    if len(head) < 20:
        raise ValueError("short audiowaveform header")
    version, flags, sample_rate, spp, length = struct.unpack("<iIiII", head[:20])
    if version == 1:
        channels = 1
        header_size = 20
    elif version == 2:
        if len(head) < 24:
            raise ValueError("short v2 audiowaveform header")
        channels = struct.unpack("<i", head[20:24])[0]
        header_size = 24
    else:
        raise ValueError(f"unsupported audiowaveform dat version: {version}")
    return {
        "version": version,
        "flags": flags,
        "sample_rate": sample_rate,
        "samples_per_pixel": spp,
        "length": length,
        "channels": channels,
        "bits": 8 if (flags & 0x1) else 16,
        "header_size": header_size,
    }


def read_peaks_int8(dat: Path) -> tuple[dict, bytes]:
    """Return (header, raw int8 min/max payload).

    Mono v1 => 2*length bytes (min,max per bucket). Stereo v2 => 4*length
    bytes (minL,maxL,minR,maxR per bucket). Caller iterates bytes
    interpreting them as int8 (`v if v < 128 else v - 256`).
    """
    head = read_header(dat)
    if not (head["flags"] & 0x1):
        raise ValueError("expected 8-bit peak data; got 16-bit")
    with open(dat, "rb") as f:
        f.seek(head["header_size"])
        body = f.read()
    return head, body


# ── Peak from .dat ───────────────────────────────────────────────────────

def peak_db_from_dat(dat: Path) -> Optional[float]:
    """Return album-level peak in dBFS or None if every bucket is silent.

    Mid-bin reconstruction: each int8 value v encodes the int16 bin
    [v*256, v*256+255]; the unbiased estimator is (v*256 + 127.5)/32768.
    Worst-case error within 6 dB of full scale is ±0.07 dB — well under
    the 1 dB precision shown in the editor.
    """
    try:
        _, body = read_peaks_int8(dat)
    except Exception:
        return None
    peak_int = 0
    for byte in body:
        v = byte if byte < 128 else byte - 256
        a = -v if v < 0 else v
        if a > peak_int:
            peak_int = a
    if peak_int <= 0:
        return None
    amp = (peak_int * 256 + 127.5) / 32768.0
    return 20.0 * math.log10(min(1.0, amp))


# ── Silence-run scan ─────────────────────────────────────────────────────

def silence_runs_from_dat(
    dat: Path,
    threshold_int8: int,
    min_duration_s: float,
) -> list[dict]:
    """Walk the .dat and emit `[{start, end, duration}, ...]` for every run
    of buckets whose absolute envelope `max(|min|, |max|)` (combined across
    all channels) stays below `threshold_int8` for at least
    `min_duration_s` seconds.

    Returns the same shape as `parse_silencedetect()` so the wave-editor's
    silence-band rendering doesn't need to branch on the producer.
    """
    if threshold_int8 <= 0:
        return []
    try:
        head, body = read_peaks_int8(dat)
    except Exception:
        return []
    sample_rate = head["sample_rate"] or 1
    spp = head["samples_per_pixel"] or 1
    length = head["length"]
    channels = max(1, head.get("channels") or 1)
    bucket_seconds = spp / sample_rate
    if bucket_seconds <= 0:
        return []
    bucket_bytes = 2 * channels  # min,max per channel, all int8
    out: list[dict] = []
    run_start: Optional[float] = None
    n = min(length, len(body) // bucket_bytes)
    for i in range(n):
        # Combined envelope across all channels: pick the loudest extreme.
        level = 0
        base = i * bucket_bytes
        for c in range(channels):
            mn = body[base + 2 * c]
            mx = body[base + 2 * c + 1]
            if mn >= 128: mn -= 256
            if mx >= 128: mx -= 256
            a = -mn if mn < 0 else mn
            if a > level: level = a
            a = -mx if mx < 0 else mx
            if a > level: level = a
        t_start = i * bucket_seconds
        if level < threshold_int8:
            if run_start is None:
                run_start = t_start
        elif run_start is not None:
            end = t_start
            if end - run_start >= min_duration_s:
                out.append({"start": run_start, "end": end,
                            "duration": end - run_start})
            run_start = None
    if run_start is not None:
        end = n * bucket_seconds
        if end - run_start >= min_duration_s:
            out.append({"start": run_start, "end": end,
                        "duration": end - run_start})
    return out
