"""Peak data: render, parse, and scan 8-bit min/max waveform .dat files.

The wave editor renders the album waveform on a `<canvas>` from a single
`.peaks.dat` file generated by BBC `audiowaveform` against the album's
concat cache (`in-progress/<album_id>/.cache/concat.flac`). The same .dat
backs silence detection (server-side scan, no ffmpeg subprocess) and the
approximate peak readout shown in the editor before the user clicks
measure.

Format: BBC audiowaveform v2 binary. Header is 24 bytes (little-endian)
followed by `2 * length * channels` signed int8 min/max samples. We always
pre-mix to mono via `ffmpeg -ac 1` so the body is exactly `2 * length`
bytes. See https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md.
"""
import math
import os
import struct
import subprocess
from pathlib import Path
from typing import Optional

# Resolution of the precomputed peak data:
#   * `-z 256` = 256 input samples per bucket (≈ 2.67 ms at 96 kHz). With a
#     2400 px canvas a 0.5 s window puts ~13 px under each bucket — visibly
#     stair-stepped at deepest zoom but still 50× finer than the 0.01 s
#     split-cut display precision the editor exposes.
#   * `-b 8` = int8 min/max per bucket. 256 amplitude levels covers the
#     140 px canvas height with headroom and halves the .dat size vs. -b 16.
PEAKS_SAMPLES_PER_PIXEL = 256
PEAKS_BITS = 8


def render_peaks(src: Path, out_dat: Path) -> None:
    """Run `ffmpeg | audiowaveform` to produce an 8-bit mono .peaks.dat at
    `out_dat`. Atomic via .tmp + os.replace so a crash mid-render leaves
    either the previous file or nothing — never a half-written .dat that
    the parser would accept and mis-render."""
    out_dat.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_dat.with_suffix(".dat.tmp")
    ff = subprocess.Popen(
        ["ffmpeg", "-loglevel", "error",
         "-i", str(src),
         "-ac", "1",
         "-f", "wav", "-"],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    aw = subprocess.Popen(
        ["audiowaveform", "--input-format", "wav", "-i", "-",
         "-o", str(tmp),
         "-z", str(PEAKS_SAMPLES_PER_PIXEL),
         "-b", str(PEAKS_BITS),
         "--output-format", "dat"],
        stdin=ff.stdout, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
    )
    if ff.stdout:
        ff.stdout.close()  # let ffmpeg see SIGPIPE if aw exits early
    aw_err = (aw.communicate()[1] or b"")
    ff_err = (ff.stderr.read() if ff.stderr else b"") or b""
    ff.wait()
    if aw.returncode != 0 or ff.returncode != 0:
        try: tmp.unlink(missing_ok=True)
        except Exception: pass
        msg = (aw_err or ff_err).decode("utf-8", errors="replace")[:500]
        raise RuntimeError(f"audiowaveform failed: {msg or 'unknown error'}")
    if not tmp.exists() or tmp.stat().st_size <= 24:
        try: tmp.unlink(missing_ok=True)
        except Exception: pass
        raise RuntimeError("audiowaveform produced empty output")
    os.replace(tmp, out_dat)


def is_fresh(dat: Path, src: Path) -> bool:
    """Cache-validity check used by callers: the .dat counts as fresh iff
    it exists and is at least as new as its source FLAC. Returns False if
    either path is missing — defensive against stat() races."""
    try:
        return dat.exists() and dat.stat().st_mtime >= src.stat().st_mtime
    except FileNotFoundError:
        return False


# ── Header parser ────────────────────────────────────────────────────────

def read_header(dat: Path) -> dict:
    """Parse the audiowaveform v2 binary header (24 bytes, little-endian).

    Layout: i32 version, u32 flags, i32 sample_rate, i32 samples_per_pixel,
    u32 length, i32 channels. We require flags' bit 0 = 1 (8-bit data) since
    every helper downstream assumes int8 min/max.
    """
    with open(dat, "rb") as f:
        head = f.read(24)
    if len(head) < 24:
        raise ValueError("short audiowaveform header")
    version, flags, sample_rate, spp, length, channels = struct.unpack(
        "<iIiIIi", head,
    )
    return {
        "version": version,
        "flags": flags,
        "sample_rate": sample_rate,
        "samples_per_pixel": spp,
        "length": length,
        "channels": channels,
        "bits": 8 if (flags & 0x1) else 16,
    }


def read_peaks_int8(dat: Path) -> tuple[dict, bytes]:
    """Return (header, raw int8 min/max payload).

    Mono => 2*length bytes. Caller iterates bytes interpreting them as
    int8 (`v if v < 128 else v - 256`)."""
    with open(dat, "rb") as f:
        head = f.read(24)
        if len(head) < 24:
            raise ValueError("short audiowaveform header")
        version, flags, sample_rate, spp, length, channels = struct.unpack(
            "<iIiIIi", head,
        )
        if not (flags & 0x1):
            raise ValueError("expected 8-bit peak data; got 16-bit")
        body = f.read()
    return (
        {"version": version, "flags": flags, "sample_rate": sample_rate,
         "samples_per_pixel": spp, "length": length, "channels": channels,
         "bits": 8},
        body,
    )


# ── Peak from .dat ───────────────────────────────────────────────────────

def peak_db_from_dat(dat: Path) -> Optional[float]:
    """Return album-level peak in dBFS or None if every bucket is silent.

    Mid-bin reconstruction: each int8 value v encodes the int16 bin
    [v*256, v*256+255]; the unbiased estimator is (v*256 + 127.5)/32768.
    Worst-case error within 6 dB of full scale is ±0.07 dB — well under
    the 1 dB precision shown in the editor.
    """
    try:
        _, body = read_peaks_int8(dat)
    except Exception:
        return None
    peak_int = 0
    for byte in body:
        v = byte if byte < 128 else byte - 256
        a = -v if v < 0 else v
        if a > peak_int:
            peak_int = a
    if peak_int <= 0:
        return None
    amp = (peak_int * 256 + 127.5) / 32768.0
    return 20.0 * math.log10(min(1.0, amp))


# ── Silence-run scan ─────────────────────────────────────────────────────

def silence_runs_from_dat(
    dat: Path,
    threshold_int8: int,
    min_duration_s: float,
) -> list[dict]:
    """Walk the .dat and emit `[{start, end, duration}, ...]` for every run
    of buckets whose absolute envelope `max(|min|, |max|)` stays below
    `threshold_int8` for at least `min_duration_s` seconds.

    Returns the same shape as `parse_silencedetect()` so the wave-editor's
    silence-band rendering doesn't need to branch on the producer.
    """
    if threshold_int8 <= 0:
        return []
    try:
        head, body = read_peaks_int8(dat)
    except Exception:
        return []
    sample_rate = head["sample_rate"] or 1
    spp = head["samples_per_pixel"] or 1
    length = head["length"]
    bucket_seconds = spp / sample_rate
    if bucket_seconds <= 0:
        return []
    out: list[dict] = []
    run_start: Optional[float] = None
    n = min(length, len(body) // 2)
    for i in range(n):
        mn = body[2 * i]
        mx = body[2 * i + 1]
        if mn >= 128: mn -= 256
        if mx >= 128: mx -= 256
        level = max(-mn, mx, 0)
        t_start = i * bucket_seconds
        if level < threshold_int8:
            if run_start is None:
                run_start = t_start
        elif run_start is not None:
            end = t_start
            if end - run_start >= min_duration_s:
                out.append({"start": run_start, "end": end,
                            "duration": end - run_start})
            run_start = None
    if run_start is not None:
        end = n * bucket_seconds
        if end - run_start >= min_duration_s:
            out.append({"start": run_start, "end": end,
                        "duration": end - run_start})
    return out
